name: NTA learning

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 --decode > private_key.pem
          chmod 600 private_key.pem

      - name: Setup Environment Variables
        run: |
          echo "EC2_HOST=${{ secrets.EC2_HOST }}" >> $GITHUB_ENV
          echo "EC2_USER=${{ secrets.EC2_USER }}" >> $GITHUB_ENV

      - name: Deploy to EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no "$EC2_USER@$EC2_HOST" << 'EOF'
            cd /var/www/html/nta-learning
            git pull origin main
            npm install
            npm run build
          EOF
          rm -rf private_key.pem
